#include $(SUBDIR)../config.mak
DESC = FFmpeg service  library
NAME = ffservice

HEADERS = ffservice.h           \


OBJS +=                  \
    ffmpeg.o        \
    ffmpeg_dec.o        \
    ffmpeg_demux.o      \
    ffmpeg_enc.o        \
    ffmpeg_filter.o     \
    ffmpeg_hw.o         \
    ffmpeg_mux.o        \
    ffmpeg_mux_init.o   \
    ffmpeg_opt.o        \
    ffmpeg_sched.o      \
    objpool.o           \
    sync_queue.o        \
    thread_queue.o      \
    cmdutils.o      \
    opt_common.o      \
    ffplay.o      \

OBJS += ffplay_renderer.o